name: build PDF

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install texlive
      run: |
        sudo apt-get install texlive-latex-extra texlive-fonts-extra
    - name: Build paper
      run: make
