# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

name: build PDF

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install texlive
      run: |
        sudo apt-get install texlive-latex-extra texlive-fonts-extra
    - name: Build paper
      run: |
        touch references.bib
        make
